version: "2.3"
services:
  confd:
    restart: always
    image: "openlan:latest"
    privileged: true
    entrypoint: ["/var/openlan/script/confd.sh", "start"]
    # network_mode: "host"
    volumes:
      - /opt/openlan/confd:/var/openlan/confd
      - /opt/openlan/etc/openlan:/etc/openlan
    ports:
      - 10000:10000
      - 10002:10002
  ovsdb-server:
    restart: always
    image: "openlan:latest"
    privileged: true
    entrypoint: ["/var/openlan/script/ovsdb-server.sh", "start"]
    # network_mode: "host"
    network_mode: service:confd
    volumes:
      - /opt/openlan/run/openvswitch:/run/openvswitch
      - /opt/openlan/etc/openvswitch:/etc/openvswitch
    depends_on:
      - confd
  ovs-vswitchd:
    restart: always
    image: "openlan:latest"
    privileged: true
    # network_mode: "host"
    network_mode: service:confd
    entrypoint: ["/var/openlan/script/ovs-vswitchd.sh", "start"]
    volumes:
      - /opt/openlan/run/openvswitch:/run/openvswitch
    depends_on:
      - confd
      - ovsdb-server
  switch:
    restart: always
    image: "openlan:latest"
    privileged: true
    # network_mode: "host"
    network_mode: service:confd
    entrypoint: ["/var/openlan/script/switch.sh", "start"]
    # stop_grace_period: 30s
    # environment:
    #   - ESPUDP=4600
    volumes:
      - /opt/openlan/confd:/var/openlan/confd
      - /opt/openlan/run/openvswitch:/run/openvswitch
      - /opt/openlan/etc/openvswitch:/etc/openvswitch
      - /opt/openlan/etc/openlan:/etc/openlan
    depends_on:
      - confd
      - ovsdb-server
      - ovs-vswitchd
