version: "2.3"
services:
  ovsdb-server:
    image: "openlan:latest"
    entrypoint: ["/var/openlan/script/ovsdb-server.sh", "start"]
    volumes:
      - /opt/openlan/run/openvswitch:/run/openvswitch
      - /opt/openlan/etc/openvswitch:/etc/openvswitch
  ovs-vswitchd:
    image: "openlan:latest"
    privileged: true
    entrypoint: ["/var/openlan/script/ovs-vswitchd.sh", "start"]
    volumes:
      - /opt/openlan/run/openvswitch:/run/openvswitch
    depends_on:
      - ovsdb-server
  confd:
    image: "openlan:latest"
    entrypoint: ["/var/openlan/script/confd.sh", "start"]
    volumes:
      - /opt/openlan/confd:/var/openlan/confd
      - /opt/openlan/etc/openlan:/etc/openlan
  switch:
    image: "openlan:latest"
    privileged: true
    entrypoint: ["/var/openlan/script/switch.sh", "start"]
    ports:
      - 10000:10000
      - 10002:10002
    volumes:
      - /opt/openlan/confd:/var/openlan/confd
      - /opt/openlan/run/openvswitch:/run/openvswitch
      - /opt/openlan/etc/openvswitch:/etc/openvswitch
      - /opt/openlan/etc/openlan:/etc/openlan
    depends_on:
      - confd
      - ovsdb-server
      - ovs-vswitchd
