name: Ubuntu CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup golang
      uses: actions/setup-go@v3
      with:
        go-version: '1.16.x'

    - name: Building packages
      run: |
        sudo apt update
        sudo apt install -y liblzo2-dev libpam-dev
        sudo apt install -y graphviz autoconf automake bzip2 debhelper dh-autoreconf libssl-dev libtool openssl procps python-all python-six libunbound-dev
        make update && make test && make linux-bin

